name: ismail_portfolio
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1
environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  animated_text_kit: ^4.2.2
  fluttertoast: ^8.2.4
  connectivity_plus: ^5.0.1
  shared_preferences: ^2.2.2
  get_it: ^7.6.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/

  fonts:
    - family: Outfit
      fonts:
        - asset: assets/fonts/Outfit-ExtraBold.ttf
        - weight: 800
        - asset: assets/fonts/Outfit-ExtraBold.ttf
        - weight: 700
        - asset: assets/fonts/Outfit-ExtraBold.ttf
        - weight: 600
        - asset: assets/fonts/Outfit-ExtraBold.ttf
        - weight: 500
        - asset: assets/fonts/Outfit-Bold.ttf
        - weight: 400
        - asset: assets/fonts/Outfit-Medium.ttf
        - weight: 300
        - asset: assets/fonts/Outfit-Regular.ttf
        - weight: 200
        - asset: assets/fonts/Outfit-Light.ttf
        - weight: 100
    


